[tool.poetry]
name = "bookstore"
version = "0.1.0"
description = ""
authors = ["Patrick Passarella <pshaggy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pendulum = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
