# Generated by Django 4.1.2 on 2022-12-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="active",
            new_name="activate",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="active",
            new_name="activate",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.AddField(
            model_name="category",
            name="price",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
